
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('cards').del()
    .then(function () {
      // Inserts seed entries
      return knex('cards').insert([
        {name: 'Brasil', url: 'https://cdn.countryflags.com/thumbs/brazil/flag-400.png',population: 209300000, area: 8511000, hdi:0.761, pop_density:25, safety_index:31.12, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/BRA_orthographic.svg/800px-BRA_orthographic.svg.png',language:'Português', currency: 'real'},
        {name: 'EUA'   , url: 'https://cdn.countryflags.com/thumbs/united-states-of-america/flag-800.png',population: 326625000, area: 9826000, hdi:0.920, pop_density:34, safety_index:52.80, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/USA_orthographic.svg/800px-USA_orthographic.svg.png', language:'Inglês', currency:'Dólar'},
        {name: 'México', url: 'https://cdn.countryflags.com/thumbs/mexico/flag-800.png',population: 124574000, area: 1964000, hdi:0.767, pop_density:64, safety_index:46.03, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/MEX_orthographic.svg/800px-MEX_orthographic.svg.png',language:'Espanhol', currency:'Peso Mexicano'},
        {name: 'Japão' , url: 'https://cdn.countryflags.com/thumbs/japan/flag-800.png',population:  126451000, area: 377000, hdi: 0.915, pop_density:334, safety_index:79.34, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Japan_%28orthographic_projection%29.svg/800px-Japan_%28orthographic_projection%29.svg.png', language: 'Japonês', currency:'Iene'},
        {name: 'França', url: 'https://cdn.countryflags.com/thumbs/france/flag-800.png',population:  62814000, area: 212000, hdi:0.891, pop_density:123, safety_index:53.08, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/EU-France_%28orthographic_projection%29.svg/800px-EU-France_%28orthographic_projection%29.svg.png', language:'Francês', currency: 'Euro'},
        {name: 'Itália', url: 'https://cdn.countryflags.com/thumbs/italy/flag-800.png',population:  62137000, area: 301000, hdi:0.883, pop_density:200, safety_index:55.74, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/EU-Italy_%28orthographic_projection%29.svg/800px-EU-Italy_%28orthographic_projection%29.svg.png', language:'Italiano', currency:'Euro'},
        {name: 'Rússia', url: 'https://cdn.countryflags.com/thumbs/russia/flag-800.png',population:  142257000, area: 17098000,hdi: 0.824, pop_density:9, safety_index:58.88, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Russian_Federation_%28orthographic_projection%29_-_Crimea_disputed.svg/270px-Russian_Federation_%28orthographic_projection%29_-_Crimea_disputed.svg.png', language:'Russo', currency: 'Rublo'},
        {name: 'China' , url: 'https://cdn.countryflags.com/thumbs/china/flag-800.png',population:   1379302000, area: 9597000, hdi:0.758, pop_density:145, safety_index:68.17, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/CHN_orthographic.svg/800px-CHN_orthographic.svg.png', language:'Mandarim', currency: 'Renminbi'},
        {name: 'India' , url: 'https://cdn.countryflags.com/thumbs/india/flag-800.png',population: 1281935000, area: 3287000, hdi:0.647,pop_density:414, safety_index:56.68, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/India_%28orthographic_projection%29.svg/800px-India_%28orthographic_projection%29.svg.png',language:'Hindi/Inglês', currency: 'Rupia'},
        {name: 'Noruega', url: 'https://cdn.countryflags.com/thumbs/norway/flag-800.png',population: 5328000, area: 323000, hdi:0.954,pop_density:16, safety_index:64.57, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Europe-Norway_%28orthographic_projection%29.svg/800px-Europe-Norway_%28orthographic_projection%29.svg.png', language:'Norueguês', currency:'Coroa Norueguesa'},
        {name: 'Bangladesh', url: 'https://cdn.countryflags.com/thumbs/bangladesh/flag-800.png',population: 157826000, area: 147570, hdi:0.614,pop_density:1070 , safety_index:36.23, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Bangladesh_on_the_globe_%28Bangladesh_centered%29.svg/800px-Bangladesh_on_the_globe_%28Bangladesh_centered%29.svg.png',language:'Bengali', currency:'Taka'},
        {name: 'Mônaco', url: 'https://cdn.countryflags.com/thumbs/monaco/flag-800.png',population: 30645, area: 2, hdi:0.956,pop_density:39292 , safety_index:68.00, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Monaco_in_Europe_%28zoomed%29.svg/800px-Monaco_in_Europe_%28zoomed%29.svg.png', language: 'Francês', currency: 'Euro'},
        {name: 'Singapura', url: 'https://cdn.countryflags.com/thumbs/singapore/flag-800.png',population: 5888000, area: 716, hdi:0.935,pop_density:8225 , safety_index:69.43, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Singapore_in_its_region_%28zoom%29.svg/1920px-Singapore_in_its_region_%28zoom%29.svg.png', language: 'Malaio/Inglês/Mandarin', currency:'Dolar de Singapura'},
        {name: 'África do sul', url: 'https://cdn.countryflags.com/thumbs/south-africa/flag-800.png',population: 54841000, area: 1221000, hdi:0.705,pop_density:45 , safety_index:22.51, map: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/ZAF_orthographic.svg/800px-ZAF_orthographic.svg.png', language:'Africâner/Inglês', currency: 'Rand'},
        {name: 'Islândia', url: 'https://cdn.countryflags.com/thumbs/iceland/flag-800.png',population: 339000, area: 103000, hdi:0.938,pop_density:3 , safety_index:76.64, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Iceland_%28orthographic_projection%29.svg/270px-Iceland_%28orthographic_projection%29.svg.png', language:'Islandês', currency: 'Coroa Islandesa'},
        {name: 'Irã', url: 'https://cdn.countryflags.com/thumbs/iran/flag-800.png',population:  82021000, area: 1628000, hdi:0.797,pop_density:50 , safety_index:50.75, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Iran_%28orthographic_projection%29.svg/270px-Iran_%28orthographic_projection%29.svg.png', language:'Persa', currency:'Rial iraniano'},
        {name: 'Peru', url: 'https://cdn.countryflags.com/thumbs/peru/flag-800.png',population:  31036000, area: 1285000, hdi:0.759,pop_density:24 , safety_index:31.85, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/PER_orthographic.svg/270px-PER_orthographic.svg.png', language:'Castelhano', currency:'Sol'},
        {name: 'Colombia', url: 'https://cdn.countryflags.com/thumbs/colombia/flag-800.png',population:  47698000, area: 1141000, hdi:0.761,pop_density:42 , safety_index:45.21, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/COL_orthographic_%28San_Andrés_and_Providencia_special%29.svg/270px-COL_orthographic_%28San_Andrés_and_Providencia_special%29.svg.png', language:'Espanhol', currency:'Peso colombiano'},
        {name: 'Jamaica', url: 'https://cdn.countryflags.com/thumbs/jamaica/flag-800.png',population:  2990000, area: 10000 , hdi:0.726,pop_density:272 , safety_index:33.96, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Jamaica_%28orthographic_projection%29.svg/800px-Jamaica_%28orthographic_projection%29.svg.png', language:'Inglês', currency: 'Dólar jamaicano'},
        {name: 'Tailândia', url: 'https://cdn.countryflags.com/thumbs/thailand/flag-800.png',population:  68414135, area: 513000 , hdi:0.765,pop_density:133 , safety_index:59.52, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Thailand_%28orthographic_projection%29.svg/800px-Thailand_%28orthographic_projection%29.svg.png', language:'Tailandês', currency:'Bate'},
        {name: 'Cuba', url: 'https://cdn.countryflags.com/thumbs/cuba/flag-800.png',population:  11147000, area: 109000 , hdi:0.778,pop_density:101 , safety_index:72.55, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Cuba_on_the_globe_%28Americas_centered%29.svg/800px-Cuba_on_the_globe_%28Americas_centered%29.svg.png', language:'Espanhol', currency:'Peso'},
        {name: 'Espanha', url: 'https://cdn.countryflags.com/thumbs/spain/flag-800.png',population: 48958000, area: 505992 , hdi:0.893,pop_density:97 , safety_index:68.04, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/EU-Spain_%28orthographic_projection%29.svg/800px-EU-Spain_%28orthographic_projection%29.svg.png', language:'Espanhol', currency: 'Euro'},
        {name: 'Etiópia', url: 'https://cdn.countryflags.com/thumbs/ethiopia/flag-800.png',population: 105350000, area: 1104300 , hdi:0.470,pop_density:95 , safety_index:50.79, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Location_Ethiopia_AU_Africa.svg/800px-Location_Ethiopia_AU_Africa.svg.png', language:'Amárico',currency: 'Birr etíope'},
        {name: 'Nova Zelândia', url: 'https://cdn.countryflags.com/thumbs/new-zealand/flag-800.png',population:  4510000, area: 275000 , hdi:0.921,pop_density:16 , safety_index:59.07, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/NZL_orthographic_NaturalEarth.svg/800px-NZL_orthographic_NaturalEarth.svg.png', language: 'Inglês/Maori', currency: 'Dólar da Nova Zelândia'},
        {name: 'Bulgária', url: 'https://cdn.countryflags.com/thumbs/bulgaria/flag-800.png',population: 7101510, area: 110879, hdi:0.816,pop_density:64 , safety_index:61.50, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Bulgaria_in_European_Union.svg/270px-Bulgaria_in_European_Union.svg.png', language:'Búlgaro', currency:'Lev'},
        {name: 'Marrocos', url: 'https://cdn.countryflags.com/thumbs/morocco/flag-800.png',population: 33986000, area: 446000, hdi:0.676,pop_density:76 , safety_index:51.31, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Morocco_%28orthographic_projection%2C_WS_claimed%29.svg/800px-Morocco_%28orthographic_projection%2C_WS_claimed%29.svg.png', language:'Árabe/Bérbere', currency: 'Dirham marroquino'},
        {name: 'Austrália', url: 'https://cdn.countryflags.com/thumbs/australia/flag-800.png',population: 23232000, area: 7692024, hdi:0.938,pop_density:3 , safety_index:58.64, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Australia_with_AAT_%28orthographic_projection%29.svg/800px-Australia_with_AAT_%28orthographic_projection%29.svg.png', language:'Inglês', currency:'Dólar australiano'},
        {name: 'Canadá', url: 'https://cdn.countryflags.com/thumbs/canada/flag-800.png',population: 35623000, area: 9984670, hdi:0.922,pop_density:4 , safety_index:60.33, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/CAN_orthographic.svg/800px-CAN_orthographic.svg.png', language:'Inglês/Francês', currency:'Dólar canadense'},
        {name: 'Bósnia e Herzegovina', url: 'https://cdn.countryflags.com/thumbs/bosnia-and-herzegovina/flag-800.png',population: 3502000, area: 51000, hdi:0.769,pop_density:68 , safety_index:56.97, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bosnia_and_Herzegovina_in_Europe.svg/800px-Bosnia_and_Herzegovina_in_Europe.svg.png',language:'Bósnio, croata e sérvio', currency:'Marco convertível'},
        {name: 'Alemanha', url: 'https://cdn.countryflags.com/thumbs/germany/flag-800.png',population: 80594000, area: 357000 , hdi:0.939,pop_density:226 , safety_index:65.19, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/EU-Germany_%28orthographic_projection%29.svg/800px-EU-Germany_%28orthographic_projection%29.svg.png', language:'Alemão',currency:'Euro'},
        {name: 'Portugal', url: 'https://cdn.countryflags.com/thumbs/portugal/flag-800.png',population: 10839000, area: 92090 , hdi:0.830,pop_density:118 , safety_index:70.37, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/EU-Portugal_%28orthographic_projection%29.svg/800px-EU-Portugal_%28orthographic_projection%29.svg.png', language:'Português',currency:'Euro'},
        {name: 'Myamar', url: 'https://cdn.countryflags.com/thumbs/myanmar/flag-800.png',population: 55123000, area: 676000 , hdi:0.584,pop_density:81 , safety_index:54.14, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/LocationMyanmar.svg/1920px-LocationMyanmar.svg.png', language:'Birmanês',currency:'Quiate'},
        {name: 'Groelândia', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/250px-Flag_of_Greenland.svg.png',population: 56000, area: 2166000 , hdi:0.803,pop_density:1 , safety_index:68.69, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Greenland_%28orthographic_projection%29.svg/800px-Greenland_%28orthographic_projection%29.svg.png', language:'Groelandês',currency:'Coroa dinamarquesa'},
        {name: 'Indonésia', url: 'https://cdn.countryflags.com/thumbs/indonesia/flag-800.png',population: 260580000, area: 1910000 , hdi:0.684,pop_density:136 , safety_index:54.16, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Indonesia_%28orthographic_projection%29.svg/800px-Indonesia_%28orthographic_projection%29.svg.png', language:'Indonésio',currency:'Rupia indonésia'},
        {name: 'Coréia do Norte', url: 'https://cdn.countryflags.com/thumbs/north-korea/flag-800.png',population: 25248000, area: 120000 , hdi:0.564,pop_density:209 , safety_index:54.16, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/North_Korea_%28orthographic_projection%29.svg/536px-North_Korea_%28orthographic_projection%29.svg.png', language:'Coreano',currency:'Won norte-coreano'},
        {name: 'Coréia do Sul', url: 'https://cdn.countryflags.com/thumbs/south-korea/flag-800.png',population:  51181000, area: 100000  , hdi:0.906,pop_density:511 , safety_index:72.61, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/South_Korea_%28orthographic_projection%29.svg/800px-South_Korea_%28orthographic_projection%29.svg.png', language:'Coreano',currency:'Won'},
        {name: 'Inglaterra', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Flag_of_England.svg/1280px-Flag_of_England.svg.png',population:  55619000, area: 130395 , hdi:0.920,pop_density:307 , safety_index:56.29, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/England_in_the_UK_and_Europe.svg/800px-England_in_the_UK_and_Europe.svg.png', language:'Inglês',currency:'Libra esterlina'},
        {name: 'Turquia', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/800px-Flag_of_Turkey.svg.png',population:  75627000, area: 783562 , hdi:0.806,pop_density:96 , safety_index:56.29, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Turkey_%28orthographic_projection%29.svg/553px-Turkey_%28orthographic_projection%29.svg.png', language:'Turco',currency:'Lira turca'},        
        {name: 'Brunei', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/1920px-Flag_of_Brunei.svg.png',population:  411000 , area: 5000 , hdi:0.845, pop_density:64 , safety_index:71.25, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Brunei_in_its_region_%28special_marker%29.svg/1280px-Brunei_in_its_region_%28special_marker%29.svg.png', language:'Malaio/Inglês',currency:'Dólar de Brunei'},        
        {name: 'Eritreia', url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/1920px-Flag_of_Eritrea.svg.png',population:  4954000 , area: 121320 , hdi:0.434, pop_density:37 , safety_index:72.24, map:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Location_Eritrea_AU_Africa.svg/800px-Location_Eritrea_AU_Africa.svg.png', language:'Árabe/Tigríneo/Inglês',currency:'Nakfa'},         

        

      ]);
    });
};
